# Generated by Django 4.1.1 on 2022-10-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='CATEGORY')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(blank=True, verbose_name='Text article')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Picture')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time_created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time_updated')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is_published')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Popular animal',
                'verbose_name_plural': 'Popular animals',
                'ordering': ['id'],
            },
        ),
    ]
